name: run main.py

on:
  workflow_dispatch:         # 👈 enables manual triggering via GitHub UI
  schedule:
    - cron: '0 0 * * 1'      # At 00:00 on Monday (UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python main.py
